Add eslint 5 support (#423)
* upgrade eslint-plugin-react (7.7.0 -> 7.11.0)

* The experimentalObjectRestSpread option has been deprecated

https://eslint.org/docs/user-guide/migrating-to-5.0.0#-the-experimentalobjectrestspread-option-has-been-deprecated

* nodejs 4 is no longer supported

https://eslint.org/docs/user-guide/migrating-to-5.0.0#drop-node-4

* file-finder has moved to util/file-finder

https://github.com/eslint/eslint/pull/10695

* removing invalidplugin from eslintrc.yml because of failure

AssertionError: expected [Function: executeUnsupportedPlugins] to not
throw an error but 'Error: Cannot find module
\'eslint-plugin-invalidplugin\'\nReferenced from:
/usr/src/app/integration/with_unsupported_plugins/eslintrc.yml' was thrown
at Context.<anonymous> (integration/eslint_test.js:30:53)

* updating README/package.json with eslint 5 updates

* upgrading output_mess with eslint 5 config

https://eslint.org/docs/user-guide/migrating-to-5.0.0#-the-experimentalobjectrestspread-option-has-been-deprecated

* sorting packages in README

* adding eslint-config-secure

* removing eslint-config-secure from the README of broken packages

* removing eslint-config-secure again

* Add fresh yarn.lock (#1)