removing invalidplugin from eslintrc.yml because of failure
AssertionError: expected [Function: executeUnsupportedPlugins] to not
throw an error but 'Error: Cannot find module
\'eslint-plugin-invalidplugin\'\nReferenced from:
/usr/src/app/integration/with_unsupported_plugins/eslintrc.yml' was thrown
at Context.<anonymous> (integration/eslint_test.js:30:53)